package com.oocourse.specs3;

/**
 * 指令类型枚举
 */
public enum InstructionType {
    PATH_ADD,
    PATH_REMOVE,
    PATH_REMOVE_BY_ID,
    PATH_GET_ID,
    PATH_GET_BY_ID,
    PATH_COUNT,
    PATH_SIZE,
    PATH_DISTINCT_NODE_COUNT,
    PATH_CONTAINS_NODE,
    CONTAINS_PATH,
    CONTAINS_PATH_ID,
    DISTINCT_NODE_COUNT,
    COMPARE_PATHS,
    CONTAINS_NODE,
    CONTAINS_EDGE,
    IS_NODE_CONNECTED,
    SHORTEST_PATH_LENGTH,
    CONNECTED_BLOCK_COUNT,
    LEAST_TICKET_PRICE,
    LEAST_TRANSFER_COUNT,
    LEAST_UNPLEASANT_VALUE,
}
